version: 0.0
os: linux 

files:
  - source: ./
    destination: /home/ubuntu
hooks:
  ApplicationStop:
    - location: Scripts/applicationStop.sh
      timeout: 500
      runas: ubuntu
  AfterInstall:
    - location: Scripts/afterInstall.sh     
      timeout: 500
      runas: ubuntu
    - location: Scripts/applicationStart.sh     
      timeout: 100
      runas: ubuntu
  ApplicationStart:
    - location: Scripts/applicationAfterStart.sh     
      timeout: 100
      runas: ubuntu