version: 0.0
os: linux 

files:
  - source: ./
    destination: /home/ubuntu
hooks:
  ApplicationStop:
    - location: ./applicationStop.sh
      timeout: 200
      runas: ubuntu
  AfterInstall:
    - location: ./afterInstall.sh     
      timeout: 200
      runas: ubuntu
  ApplicationStart:
    - location: ./applicationStart.sh
    - runas: ubuntu