version: 0.0
os: linux 

files:
  - source: ./
    destination:  /home/ubuntu
hooks:

  # ApplicationStop:
  #   - location: 
  #     timeout:
  #     runas:
  #   - location: 
  #     timeout:
  #     runas:
  AfterInstall:
    - location: Scripts/afterInstall.sh     
      timeout: 200
      runas: ubuntu