version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: ls
      - run: cd backend
      - node/with-cache:
          steps:
            - run: cd backend && npm install
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend
      - node/with-cache:
          steps:
            - run: cd backend && npm install
            - run: cd backend && npm test
workflows:
    pr_check:
      jobs:
        - build
        - test
